name: asift_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  go_router: ^9.0.0
  flutter_bloc: ^8.0.0
  http: ^1.1.0
  equatable: ^2.0.5
  url_strategy: ^0.2.0
  shared_preferences: ^2.1.2
  responsive_builder: ^0.7.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
